### ISSUE TITLE
Default scrollbar style with enabled Shadow DOM on OS X

### ISSUE THREAD

**Issue by Cortys** [mbullington/quantum-ui#3]
![screenshot 2015-01-14 23 55 29](https://cloud.githubusercontent.com/assets/1737630/5749403/eaf332c4-9c48-11e4-946e-3ba2e08e3514.png)

Nothing too bad. Thanks a lot for this otherwise elegant and beautiful theme.

**Comment by mbullington** [comment]
I have Shadow DOM enabled, and don't seem to have this problem. I'll try it with minimap and get back to you. 

And thanks. :)

**Comment by mbullington** [comment]
Tried with Minimap, still worked fine. Can I have a list of your packages your using with Atom?

**Comment by Cortys** [comment]
I just tried it with all community packages disabled. Still not working though. I'm currently using 0.172 but had this problem in the last few releases as well.

**Comment by mbullington** [comment]
Try updating to version v2.0.0 of quantum-ui, that should have fixed it (Shadow DOM support). :)

Also, enjoy all the changes in v2.0.0 too. If you use custom syntax themes, Quantum will attempt to match them somewhat in the tabs.

**Comment by Cortys** [comment]
Awesome. Thanks a lot!
