### ISSUE TITLE
Publish latest version to apm

### ISSUE THREAD

**Issue by Cortys** [mbullington/quantum-ui#9]
Hi! Still using your theme.

I'd really appreciate if you published e612e5450c37dff1d0e7cbba9ec8509c60e173b1 to apm. And, should you find the time, maybe #8 as well?

Thanks!

**Comment by mbullington** [comment]
Thanks for your continued support!

I'll accept #8 and publish the new version to apm. Also, considering I find the time to work on it, I've started on another theme based off of the new Atom default theme, with (I think) nicer colors, less evasive animations, etc.

**Comment by Cortys** [comment]
Great!

Looking forward to trying out your new theme.
